# Generated by Django 5.2.17 on 2026-09-27 12:46

import contracts.ids
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=contracts.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESERVED', 'Reserved'), ('PAID', 'Paid'), ('FULFILLING', 'Fulfilling'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=16)),
                ('total_tiyin', models.BigIntegerField()),
                ('delivery_address', models.JSONField()),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['customer_id', '-created_at'], name='order_customer_created_idx'), models.Index(condition=models.Q(('status', 'RESERVED')), fields=['reserved_until'], name='order_reserved_until_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_tiyin__gte', 0)), name='order_total_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('RESERVED', 'Reserved'), ('PAID', 'Paid'), ('FULFILLING', 'Fulfilling'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], max_length=16, null=True)),
                ('to_status', models.CharField(choices=[('PENDING', 'Pending'), ('RESERVED', 'Reserved'), ('PAID', 'Paid'), ('FULFILLING', 'Fulfilling'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'order status history',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.UUIDField(default=contracts.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('seller_id', models.UUIDField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED_BY_SELLER', 'Cancelled_By_Seller')], default='NEW', max_length=24)),
                ('subtotal_tiyin', models.BigIntegerField()),
                ('commission_rate_snapshot', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('commission_tiyin', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='orders.order')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=contracts.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('variant_id', models.UUIDField()),
                ('seller_id', models.UUIDField()),
                ('shop_name_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('title_snapshot', models.CharField(max_length=200)),
                ('sku_snapshot', models.CharField(max_length=64)),
                ('image_snapshot', models.CharField(blank=True, default='', max_length=500)),
                ('price_snapshot_tiyin', models.BigIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('sub_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.suborder')),
            ],
            options={
                'ordering': ('seller_id', 'title_snapshot', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='suborder',
            index=models.Index(fields=['seller_id', '-created_at'], name='suborder_seller_idx'),
        ),
        migrations.AddConstraint(
            model_name='suborder',
            constraint=models.UniqueConstraint(fields=('order', 'seller_id'), name='suborder_order_seller'),
        ),
        migrations.AddConstraint(
            model_name='suborder',
            constraint=models.CheckConstraint(condition=models.Q(('commission_tiyin__gte', 0), ('subtotal_tiyin__gte', 0)), name='suborder_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='suborder',
            constraint=models.CheckConstraint(condition=models.Q(('commission_rate_snapshot__gte', 0), ('commission_rate_snapshot__lte', 1)), name='suborder_commission_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'variant_id'), name='orderitem_order_variant'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('price_snapshot_tiyin__gt', 0)), name='orderitem_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='orderitem_qty_positive'),
        ),
    ]
