# Generated by Django 5.2.17 on 2026-09-28 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubOrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED_BY_SELLER', 'Cancelled_By_Seller')], max_length=24, null=True)),
                ('to_status', models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED_BY_SELLER', 'Cancelled_By_Seller')], max_length=24)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'sub-order status history',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='suborder',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='suborder',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='suborder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='suborder',
            index=models.Index(fields=['seller_id', 'status', '-created_at'], name='suborder_seller_status_idx'),
        ),
        migrations.AddField(
            model_name='suborderstatushistory',
            name='sub_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.suborder'),
        ),
    ]
