# Generated by Django 5.2.17 on 2026-10-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_seller_fulfilment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='late_payment',
            field=models.BooleanField(default=False),
        ),
    ]
