# Generated by Django 5.2.17 on 2026-09-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('correlation_id', models.UUIDField()),
                ('occurred_at', models.DateTimeField()),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(condition=models.Q(('published_at__isnull', True)), fields=['id'], name='outbox_unpublished_idx')],
            },
        ),
    ]
