# Generated by Django 5.2.17 on 2026-09-22 18:25

import accounts.models
import accounts.phone
import contracts.ids
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=contracts.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=16, unique=True, validators=[accounts.phone.validate_e164_phone])),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller'), ('admin', 'Admin')], default='customer', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('date_joined',),
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.UUIDField(default=contracts.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=16)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['phone', '-created_at'], name='otp_phone_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.UUIDField(default=contracts.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'outbox',
                'indexes': [models.Index(condition=models.Q(('published_at__isnull', True)), fields=['created_at'], name='outbox_unpublished_idx')],
            },
        ),
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.UUIDField(default=contracts.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=120)),
                ('inn', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'INN must be exactly 9 digits.')])),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_seller_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='application_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='one_pending_application_per_user')],
            },
        ),
    ]
