# Generated by Django 5.2.17 on 2026-10-09 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=32, validators=[django.core.validators.RegexValidator('^-?\\d{1,20}$', 'Telegram chat id must be a number.')]),
        ),
    ]
