# Generated by Django 5.2.17 on 2026-10-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreservation',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
