# Generated by Django 5.2.17 on 2026-09-22 18:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(unique=True)),
                ('shop_name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('shop_name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('commission_rate__gte', 0), ('commission_rate__lte', 1)), name='seller_commission_rate_range'), models.CheckConstraint(condition=models.Q(('id', models.F('user_id'))), name='seller_id_is_user_id')],
            },
        ),
    ]
