"""initial payment tables

Revision ID: 039db66888d2
Revises:
Create Date: 2026-10-09 16:35:26.089613
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '039db66888d2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox')),
    sa.UniqueConstraint('event_id', name=op.f('uq_outbox_event_id'))
    )
    op.create_index('ix_outbox_unpublished', 'outbox', ['id'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_table('processed_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_processed_events'))
    )
    op.create_table('seller_payouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('gross_tiyin', sa.BigInteger(), nullable=False),
    sa.Column('commission_tiyin', sa.BigInteger(), nullable=False),
    sa.Column('net_tiyin', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seller_payouts')),
    sa.UniqueConstraint('seller_id', 'period_start', name='uq_seller_payouts_seller_period')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('amount_tiyin', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.SmallInteger(), nullable=False),
    sa.Column('provider_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('perform_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_tiyin > 0', name=op.f('ck_transactions_amount_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('number', name=op.f('uq_transactions_number')),
    sa.UniqueConstraint('provider', 'external_id', name='uq_transactions_provider_external_id')
    )
    op.create_index('ix_transactions_order_id', 'transactions', ['order_id'], unique=False)
    op.create_index('ix_transactions_provider_create_time', 'transactions', ['provider', 'create_time'], unique=False)
    op.create_index('uq_transactions_active_order', 'transactions', ['order_id'], unique=True, postgresql_where=sa.text('state = 1'))
    op.create_table('payout_lines',
    sa.Column('sub_order_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('gross_tiyin', sa.BigInteger(), nullable=False),
    sa.Column('commission_tiyin', sa.BigInteger(), nullable=False),
    sa.Column('net_tiyin', sa.BigInteger(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('payout_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payout_id'], ['seller_payouts.id'], name=op.f('fk_payout_lines_payout_id_seller_payouts')),
    sa.PrimaryKeyConstraint('sub_order_id', name=op.f('pk_payout_lines'))
    )
    op.create_index(op.f('ix_payout_lines_payout_id'), 'payout_lines', ['payout_id'], unique=False)
    op.create_index(op.f('ix_payout_lines_seller_id'), 'payout_lines', ['seller_id'], unique=False)
    op.create_index('ix_payout_lines_unassigned_delivered', 'payout_lines', ['delivered_at'], unique=False, postgresql_where=sa.text('payout_id IS NULL AND cancelled = false'))
    op.create_table('refunds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('amount_tiyin', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_tiyin > 0', name=op.f('ck_refunds_amount_positive')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_refunds_transaction_id_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds'))
    )
    op.create_index(op.f('ix_refunds_transaction_id'), 'refunds', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_transaction_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index('ix_payout_lines_unassigned_delivered', table_name='payout_lines', postgresql_where=sa.text('payout_id IS NULL AND cancelled = false'))
    op.drop_index(op.f('ix_payout_lines_seller_id'), table_name='payout_lines')
    op.drop_index(op.f('ix_payout_lines_payout_id'), table_name='payout_lines')
    op.drop_table('payout_lines')
    op.drop_index('uq_transactions_active_order', table_name='transactions', postgresql_where=sa.text('state = 1'))
    op.drop_index('ix_transactions_provider_create_time', table_name='transactions')
    op.drop_index('ix_transactions_order_id', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('seller_payouts')
    op.drop_table('processed_events')
    op.drop_index('ix_outbox_unpublished', table_name='outbox', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_table('outbox')
    # ### end Alembic commands ###
